#!/bin/bash
export EDITOR=nano
echo "installing rofi and picom from main repo"
sudo pacman -S rofi picom
echo "installing polybar from aur"
pacaur -S polybar siji-git
mkdir -p ~/.config/i3
mkdir -p ~/.config/rofi
mkdir -p ~/.config/polybar
mkdir -p ~/.config/picom
cp polybar/config ~/.config/polybar/config
cp i3/config ~/.config/i3/config
cp rofi/config ~/.config/rofi/config
cp .xinitrc ~/
sudo cp loadbar /usr/local/bin/loadbar
cp picom/picom.conf ~/.config/picom/picom.conf
