#!/bin/bash
echo "installing rofi from main repo"
sudo pacman -S rofi
echo "installing polybar from aur"
pacaur -S polybar
mkdir -p ~/.config/i3
mkdir -p ~/.config/rofi
mkdir -p ~/.config/polybar
cp polybar/config ~/.config/i3/polybar
cp i3/config ~/.config/i3/config
cp rofi/config ~/.config/rofi/config
cp .xinitrc ~/
